version: "3"

# More info at https://github.com/oracle/opengrok/docker/
services:
  opengrok-1-7-11:
    container_name: opengrok-1.7.11
    image: simranchawla/opengrok-configured:1.0-SNAPSHOT
    restart: on-failure
    volumes:
      - 'opengrok_data1_7_11:/opengrok/data'
      - '/code/opengrok/src/:/opengrok/src/'  # source code
      - './etc/:/opengrok/etc/'  # folder contains configuration.xml
      - './ssh/:/root/.ssh/'
      - '.gitconfig:/root/.gitconfig'
      - '/etc/localtime:/etc/localtime:ro'
      - './logs/:/usr/local/tomcat/logs/'
      - './conf/:/usr/local/tomcat/conf'
    ports:
      - "9090:8080/tcp"
      - "5001:5000/tcp"
    environment:
      SYNC_PERIOD_MINUTES: '60'
      OPENGROK_LOG_LEVEL: 'INFO'
      NOMIRROR: 'true'
      #NO_PROXY: 'localhost,127.0.0.1,github.XXXXon.YYYYYgrp.net'
      INDEXER_OPT: '-H -P -G -R /opengrok/etc/read_only.xml'
    # Volumes store your data between container upgrades
volumes:
  opengrok_data1_7_11:
networks:
  opengrok-1-7-11:
