name: Build Docker image
on:
  push:
    branches:
      - fas-config2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          context: ./dockerfile
          file: Dockerfile
          tags: opengrok-valve:1
