name: Build Docker image
on:
  push:
    branches:
      - fas-config2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t opengrok-valve:1 ./dockerfile
